package models 

type TgAdminUserCopy1 struct { 
    Id int `xorm:"primary_key autoincr comment('') INT(11)" json:"id"` 
    IsBindWechat uint8 `xorm:"tinyint(1)" json:"is_bind_wechat"` 
    Username string `xorm:"varchar(32)" json:"username"` 
    Password string `xorm:"varchar(128)" json:"password"` 
    Token string `xorm:"varchar(128)" json:"token"` 
    Tel string `xorm:"varchar(64)" json:"tel"` 
    Attached string `xorm:"varchar(6)" json:"attached"` 
    Nickname string `xorm:"varchar(128)" json:"nickname"` 
    RealName string `xorm:"varchar(255)" json:"real_name"` 
    IsPwd uint8 `xorm:"tinyint(3)" json:"is_pwd"` 
    WechatAvatar string `xorm:"varchar(255)" json:"wechat_avatar"` 
    Avatar string `xorm:"varchar(255)" json:"avatar"` 
    BjImage string `xorm:"varchar(255)" json:"bj_image"` 
    Birth string `xorm:"date" json:"birth"` 
    Age uint8 `xorm:"tinyint(3)" json:"age"` 
    Signs string `xorm:"varchar(255)" json:"signs"` 
    RegisterArea string `xorm:"varchar(255)" json:"register_area"` 
    FollowNum int `xorm:"int(10)" json:"follow_num"` 
    FansNum int `xorm:"int(10)" json:"fans_num"` 
    Sex uint8 `xorm:"tinyint(1)" json:"sex"` 
    SignText string `xorm:"varchar(512)" json:"sign_text"` 
    Star float64 `xorm:"decimal(3,1)" json:"star"` 
    Pid int `xorm:"int(10)" json:"pid"` 
    RegisterLatitude string `xorm:"varchar(256)" json:"register_latitude"` 
    RegisterLongitude string `xorm:"varchar(256)" json:"register_longitude"` 
    MerchantType uint8 `xorm:"tinyint(3)" json:"merchant_type"` 
    Level uint8 `xorm:"tinyint(3)" json:"level"` 
    MotoLevel uint8 `xorm:"tinyint(3)" json:"moto_level"` 
    BusinessLevel string `xorm:"varchar(10)" json:"business_level"` 
    MotoBusinessLevel string `xorm:"varchar(10)" json:"moto_business_level"` 
    Terminal uint8 `xorm:"tinyint(3)" json:"terminal"` 
    CurrentCityId int `xorm:"int(10)" json:"current_city_id"` 
    IsComment uint8 `xorm:"tinyint(1)" json:"is_comment"` 
    FirstLoginTime string `xorm:"datetime" json:"first_login_time"` 
    LastLoginTime string `xorm:"datetime" json:"last_login_time"` 
    LastLoginIp string `xorm:"varchar(255)" json:"last_login_ip"` 
    RegisterIp string `xorm:"varchar(255)" json:"register_ip"` 
    LoginNum int `xorm:"int(10)" json:"login_num"` 
    IsSale uint8 `xorm:"tinyint(1)" json:"is_sale"` 
    IsModel uint8 `xorm:"tinyint(1)" json:"is_model"` 
    IsVip uint8 `xorm:"tinyint(1)" json:"is_vip"` 
    IsDoyen uint8 `xorm:"tinyint(1)" json:"is_doyen"` 
    IsMaster uint8 `xorm:"tinyint(1)" json:"is_master"` 
    IsAdmin uint8 `xorm:"tinyint(1)" json:"is_admin"` 
    Type uint8 `xorm:"tinyint(3)" json:"type"` 
    Status uint8 `xorm:"tinyint(1)" json:"status"` 
    UpdateTime string `xorm:"datetime" json:"update_time"` 
    CreateTime string `xorm:"datetime" json:"create_time"` 
    CreateBy int `xorm:"int(10)" json:"create_by"` 
    UpdateBy int `xorm:"int(10)" json:"update_by"` 
    MotoBusinessPoints int `xorm:"int(11)" json:"moto_business_points"` 
    PointsMoto int `xorm:"int(10)" json:"points_moto"` 
    KcwcBusinessPoints int `xorm:"int(11)" json:"kcwc_business_points"` 
    PointsKcwc int `xorm:"int(10)" json:"points_kcwc"` 
    Exp int `xorm:"int(10)" json:"exp"` 
    KcwcBusinessExp int `xorm:"int(11)" json:"kcwc_business_exp"` 
    MotoExp int `xorm:"int(11)" json:"moto_exp"` 
    MotoBusinessExp int `xorm:"int(11)" json:"moto_business_exp"` 
    ViewCount int `xorm:"int(10)" json:"view_count"` 
    IsActivation uint8 `xorm:"tinyint(3)" json:"is_activation"` 
    Inviter int `xorm:"int(10)" json:"inviter"` 
    DepartmentId int `xorm:"int(10)" json:"department_id"` 
    PositionId int `xorm:"int(10)" json:"position_id"` 
    AllowPush uint8 `xorm:"tinyint(1)" json:"allow_push"` 
    ContinuousLogin int `xorm:"int(11)" json:"continuous_login"` 
    OldId int `xorm:"int(10)" json:"old_id"` 
    OrgId int `xorm:"int(11)" json:"org_id"` 
    CouponOnline uint8 `xorm:"tinyint(1)" json:"coupon_online"` 
    SaleOnline uint8 `xorm:"tinyint(1)" json:"sale_online"` 
    KcwcFreezePoints int `xorm:"int(11)" json:"kcwc_freeze_points"` 
    MotoFreezePoints int `xorm:"int(11)" json:"moto_freeze_points"` 
    KcwcBusinessFreezePoints int `xorm:"int(11)" json:"kcwc_business_freeze_points"` 
    MotoBusinessFreezePoints int `xorm:"int(11)" json:"moto_business_freeze_points"` 
    UserGetPoints int `xorm:"int(11)" json:"user_get_points"` 
    UserGetBussinessPoints int `xorm:"int(11)" json:"user_get_bussiness_points"` 
    UserTotlePoints int `xorm:"int(11)" json:"user_totle_points"` 
    UserTotleBussinessPoints int `xorm:"int(11)" json:"user_totle_bussiness_points"` 
    ShowPosition string `xorm:"varchar(30)" json:"show_position"` 
    WorkArea string `xorm:"varchar(100)" json:"work_area"` 
    Work string `xorm:"varchar(100)" json:"work"` 
    HomeTown string `xorm:"varchar(100)" json:"home_town"` 
    IsOfficial uint8 `xorm:"tinyint(3)" json:"is_official"` 
    OnlineService uint8 `xorm:"tinyint(1)" json:"online_service"` 
}